**Zanim zaczniesz pracę zapisz kopię na dysku**




W tym zadaniu poćwiczymy pracę z **ramkami danych** w bibliotece **Pandas** na przykładzie zbioru `titanic.csv`.

**Plik titanic** zawiera informacje dotyczące pasażerów statku RMS Titanic, który zatonął w kwietniu 1912 roku po zderzeniu z górą lodową. Plik ten jest często używany jako zestaw danych do nauki analizy danych, modelowania przewidywań i eksploracji danych.

Typowy zestaw danych titanic zawiera nastepujące kolumny:

- PassengerId: Unikalny identyfikator pasażera.
- Survived: Informacja o tym, czy pasażer przeżył katastrofę (1 - przeżył, 0 - nie przeżył).
- Pclass: Klasa biletu pasażera (1 - pierwsza klasa, 2 - druga klasa, 3 - trzecia klasa).
- Name: Imię i nazwisko pasażera.
- Sex: Płeć pasażera.
- Age: Wiek pasażera.
- SibSp: Liczba rodzeństwa / małżonków na pokładzie.
- Parch: Liczba rodziców / dzieci na pokładzie.
- Ticket: Numer biletu.
- Fare: Cena biletu.
- Cabin: Numer kabiny pasażera.
- Embarked: Port, w którym pasażer wszedł na pokład statku (C - Cherbourg, Q - Queenstown, S - Southampton).

## Zaimportuj biblioteki: NumPy i Pandas

In [1]:
import numpy as np
import pandas as pd

## Pobierz zbiór danych ML-datasets z GitHub (Link: `https://github.com/matzim95/ML-datasets`)

In [3]:
!wget https://github.com/matzim95/ML-datasets/titanic.csv

7[Files: 0  Bytes: 0  [0 B/s] Re]8

7[https://github.com/matzim95/ML]87[Files: 0  Bytes: 0  [0 B/s] Re]87titanic.csv          100% [=============================>]       9     --.-KB/s87HTTP ERROR response 404  [https://github.com/matzim95/ML-datasets/titanic.csv]
87titanic.csv          100% [=============================>]       9     --.-KB/s87[Files: 0  Bytes: 9  [8 B/s] Re]8

Cloning into 'ML-datasets'...
remote: Enumerating objects: 201, done.
remote: Counting objects: 100% (141/141), done.
remote: Compressing objects: 100% (117/117), done.
remote: Total 201 (delta 35), reused 124 (delta 24), pack-reused 60 (from 1)
Receiving objects: 100% (201/201), 35.87 MiB | 9.84 MiB/s, done.
Resolving deltas: 100% (47/47), done.
Updating files: 100% (130/130), done.

## Załaduj plik titanic.csv z pobranego folderu i zapisz go jako zmienną titanic.
## Wyswietl 10 pierwszych wierszy

In [5]:
df = pd.read_csv('titanic.csv')

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## wyświtl rozmiar/kształt zbioru

In [7]:
print(df.shape)

(891, 12)

## wyświetlanie 3 ostatnie wiersze

In [8]:
print(df[-3:])

     PassengerId  Survived  Pclass                                      Name  \
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q

## wyswietl 3 losowe wiersze

In [71]:
print(df.iloc[[20, 60, 80]])

    PassengerId  Survived  Pclass                   Name   Sex   Age  SibSp  \
20           21         0       2   Fynney, Mr. Joseph J  male  35.0      0
60           61         0       3  Sirayanian, Mr. Orsen  male  22.0      0
80           81         0       3   Waelens, Mr. Achille  male  22.0      0

    Parch  Ticket     Fare Cabin Embarked Country  New_age
20      0  239865  26.0000   NaN        S      US     37.0
60      0    2669   7.2292   NaN        C      US     24.0
80      0  345767   9.0000   NaN        S      US     24.0

## wyświetl ogólne informacje o zbiorze

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## wyświetl statystyki opisowe

In [10]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## zakres indeksów

In [11]:
df.index

RangeIndex(start=0, stop=891, step=1)

## lista kolumn

In [12]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

## wyświetl kolumnę 'Survived'

In [14]:
df["Survived"]

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

## Wyświetl kolumny:  'Survived' i 'Pclass'

In [15]:
df[["Survived", "Pclass"]]

     Survived  Pclass
0           0       3
1           1       1
2           1       3
3           1       1
4           0       3
..        ...     ...
886         0       2
887         1       1
888         0       3
889         1       1
890         0       3

[891 rows x 2 columns]

## wyświetl wiersze o indeksach od 20 do 24 włacznie

In [16]:
df.iloc[20:25]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S

## wyświetl wszystkie kolumny dla wierszy o indeksach od 10 do 14 włacznie

In [18]:
df.iloc[10:15]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S

## wyświetl wszystkie wiersze dla kolumny o indeksie 0

In [19]:
df.iloc[:, 0]

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: PassengerId, Length: 891, dtype: int64

## wyświetl fragment DF dla wierszy o indeksach od 10 do 14 włacznie i kolumn o indeksach od 3 do 4 włącznie

In [20]:
df.iloc[10:15, 3:5]

                                    Name     Sex
10       Sandstrom, Miss. Marguerite Rut  female
11              Bonnell, Miss. Elizabeth  female
12        Saundercock, Mr. William Henry    male
13           Andersson, Mr. Anders Johan    male
14  Vestrom, Miss. Hulda Amanda Adolfina  female

## wyświetl fragment DF dla wierszy o indeksach od 10 do 14 włacznie i kolumn o indeksach od 3 do końca

In [21]:
df.iloc[10:15, 3:]

,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S

## wyświetl dfragment DF dla wierszy o indeksach od poczatku do 10 włacznie i kolumn 'Name' i 'Sex

In [22]:
df.iloc[:11][["Name", "Sex"]]

                                                 Name     Sex
0                             Braund, Mr. Owen Harris    male
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                              Heikkinen, Miss. Laina  female
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                            Allen, Mr. William Henry    male
5                                    Moran, Mr. James    male
6                             McCarthy, Mr. Timothy J    male
7                      Palsson, Master. Gosta Leonard    male
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
9                 Nasser, Mrs. Nicholas (Adele Achem)  female
10                    Sandstrom, Miss. Marguerite Rut  female

## Wyświetl tylko te wiersze, dla których wiek jest wiekszy od 20

In [23]:
df[df["Age"] > 20]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## Wyświetl tylko tych pasażerów, których wiek jest niższy niż 20 lat i podrużowali w 1 klasie

In [27]:
df[np.logical_and(df["Age"] < 20, df["Pclass"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
136,137,1,1,"Newsom, Miss. Helen Monypeny",female,19.00,0,2,11752,26.2833,D47,S
291,292,1,1,"Bishop, Mrs. Dickinson H (Helen Walton)",female,19.00,1,0,11967,91.0792,B49,C
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
329,330,1,1,"Hippach, Miss. Jean Gertrude",female,16.00,0,1,111361,57.9792,B18,C
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S
504,505,1,1,"Maioni, Miss. Roberta",female,16.00,0,0,110152,86.5000,B79,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
585,586,1,1,"Taussig, Miss. Ruth",female,18.00,0,2,110413,79.6500,E68,S
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
748,749,0,1,"Marvin, Mr. Daniel Warner",male,19.00,1,0,113773,53.1000,D30,S
781,782,1,1,"Dick, Mrs. Albert Adrian (Vera Gillespie)",female,17.00,1,0,17474,57.0000,B20,S
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
853,854,1,1,"Lines, Miss. Mary Conover",female,16.00,0,1,PC 17592,39.4000,D28,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.00,0,0,112053,30.0000,B42,S

## Podostuj DF od najmniejszej do największej wartości na podstaiwe kolumny 'Cabin'

In [28]:
df.sort_values("Cabin", ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
339,340,0,1,"Blackwell, Mr. Stephen Weart",male,45.0,0,0,113784,35.5000,T,S
394,395,1,3,"Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...",female,24.0,0,2,PP 9549,16.7000,G6,S
205,206,0,3,"Strom, Miss. Telma Matilda",female,2.0,0,1,347054,10.4625,G6,S
251,252,0,3,"Strom, Mrs. Wilhelm (Elna Matilda Persson)",female,29.0,1,1,347054,10.4625,G6,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## Podostuj DF od najmniejszej do największej wartości na podstaiwe kolumny 'Age' i wyświetl 20 pierwszych wierszy

In [29]:
df.sort_values(by="Age", ascending=False).head(20)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S

##Posortuj od największej do najmniejszej wartości na podstaiwe kolumny 'Fare'

In [ ]:
df.sort_values(by="Fare", ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
...,...,...,...,...,...,...,...,...,...,...,...,...
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0000,B102,S
466,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0000,NaN,S
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0000,NaN,S
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0000,NaN,S

# - Utwórz mową kolumny 'Country' i uzupełnij ją 'US'
# - Wyświetl 5 pierwszych wierszy

In [30]:
df["Country"] = "US"

In [31]:
df["Country"].head()

0    US
1    US
2    US
3    US
4    US
Name: Country, dtype: object

## Wyświetl kształt zbioru

In [32]:
df.shape

(891, 13)

## zlicz liczbę wystąpień w poszczególnych kategoriach dla zmiennej 'Survived'

In [42]:
df.Survived.value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

## zlicz libę kobiet i mężczyzn

In [43]:
df.Sex.value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

## zlicz liczbę nienulowych wartości dla zmiennej 'Age'

In [46]:
df[~df.isnull()]["Age"].value_counts()

Age
24.00    30
22.00    27
18.00    26
28.00    25
30.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

## minimalna wartość dla zmiennej wiek

In [47]:
df["Age"].min()

0.42

## średnia dla zmiennej wiek

In [48]:
df["Age"].mean()

np.float64(29.69911764705882)

## maksymalna wartość dla zmiennej wiek

In [49]:
df["Age"].max()

80.0

## - Dodaj nową kolumnę 'New_age', w której do wieku będzie dodawane 2
# - Wyświetl 3 pierwsze wiersze

In [50]:
df["New_age"] = df["Age"] + 2

df["New_age"].head(3)

0    24.0
1    40.0
2    28.0
Name: New_age, dtype: float64

## zgrupuj dane według wartości w kolumnie 'Pclass' (klasa biletu) i obliczy średnią wartość wieku ('Age') w każdej z tych grup.

In [53]:
df.groupby("Pclass")["Age"].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

## podaj jaka była średnia wieku dla kobiet i mężczyzn w grupie osób, które przeżyły i nie przezyły

In [54]:
df.groupby(["Survived", "Pclass"])["Age"].mean()

Survived  Pclass
0         1         43.695312
          2         33.544444
          3         26.555556
1         1         35.368197
          2         25.901566
          3         20.646118
Name: Age, dtype: float64

## Ile było osbób, które przezyły w grupie kobiet i mężczyzn

In [59]:
df.Sex.value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [60]:
df[df["Survived"] == 1].Sex.value_counts()

Sex
female    233
male      109
Name: count, dtype: int64

## - Usuń kolumnę 'Country'
# - Wyswietl 4 pierwsze wiersze

In [61]:
df.drop(columns=["Country"], inplace=False).head(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,New_age
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,24.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,40.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,28.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,37.0

## wyświetl kształt zbioru

In [63]:
df.shape

(891, 14)

## - utwórz obiekt titanic_new1, do którego zapiszesz zbiór bez braków
# - wyświetl 5 pierwszych wierszy - zwróć uwagę na indeksy

In [64]:
titanic_new1 = df.dropna()

titanic_new1.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Country,New_age
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,US,40.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,US,37.0
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,US,56.0
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,US,6.0
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,US,60.0

## - w zbiorze titanic_new1 zresetuj indeksy
# - wyświetl 3 pierwsze wiersze

In [65]:
titanic_new1.reset_index().head(3)

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Country,New_age
0,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,US,40.0
1,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,US,37.0
2,6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,US,56.0

## wyświetl kształt nowego zbioru i porównaj go z poprzednim wynikiem

In [66]:
df.shape == titanic_new1.shape

False

(183, 13)

## Wyświetl 10 pierwszych wierszy ramki danych titanic

In [68]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Country,New_age
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,US,24.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,US,40.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,US,28.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,US,37.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,US,37.0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,US,NaN
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,US,56.0
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,US,4.0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,US,29.0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,US,16.0

## w orginalnym obiekcie (titanic) uzupełnij brakujące wartosci dla zmiennej 'Age' wartością średnią
## Wyswietl 10 pierwszych wierszy

In [69]:
df["Age"].fillna(df["Age"].mean()).head(10)

0    22.000000
1    38.000000
2    26.000000
3    35.000000
4    35.000000
5    29.699118
6    54.000000
7     2.000000
8    27.000000
9    14.000000
Name: Age, dtype: float64

## w zmiennej 'Cabine' braki danych uzupełnij napisem 'unknown'
## wyświetl 3 pierwsze wiersze

In [70]:
df["Cabin"].fillna("Unknown").head(3)

0    Unknown
1        C85
2    Unknown
Name: Cabin, dtype: object

# Dodaj nową kolumnę 'Age_cat', w której pojawią dwie kategorie:
# - young dla osób poniżej 35 lat
# - old dla pozostałych

# wyswietl 5 pierwszych wierszy

In [ ]:
df["Age_cat"] = df["Age"].apply(lambda x: "young" if x < 35 else "old")
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,New_age,Age_cat
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,unknown,S,24.0,young
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,40.0,old
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,unknown,S,28.0,young
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,37.0,old
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,unknown,S,37.0,old

👍